let coffeeItem = [{
    id: 'coffee1',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    subtitle: "$7.00",
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-2.svg",
    title: "Kahlua coffee",
    text: "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
    subtitle: "$7.00",
},
{
    id: 'coffee3',
    img: "../img/pictures/coffee-3.svg",
    title: "Honey raf",
    text: "Espresso with frothed milk, cream and aromatic honey",
    subtitle: "$5.50",
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    subtitle: "$7.00",
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    subtitle: "$7.00",
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    subtitle: "$7.00",
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    subtitle: "$7.00",
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    subtitle: "$7.00",
},
];