let coffeeItem = [{
    id: 'coffee1',
    img: "../img/pictures/coffee-1.svg",
    title: "Irish coffee",
    text: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    price: 7.00,
},
{
    id: 'coffee2',
    img: "../img/pictures/coffee-2.svg",
    title: "Kahlua coffee",
    text: "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
    price: 7.00,
},
{
    id: 'coffee3',
    img: "../img/pictures/coffee-3.svg",
    title: "Honey raf",
    text: "Espresso with frothed milk, cream and aromatic honey",
    price: 5.50,
},
{
    id: 'coffee4',
    img: "../img/pictures/coffee-4.svg",
    title: "Ice cappuccino",
    text: "Cappuccino with soft thick foam in summer version with ice",
    price: 5.00,
},
{
    id: 'coffee5',
    img: "../img/pictures/coffee-5.svg",
    title: "Espresso",
    text: "Espresso",
    price: 4.50,
},
{
    id: 'coffee6',
    img: "../img/pictures/coffee-6.svg",
    title: "Latte",
    text: "Espresso coffee with the addition of steamed milk and dense milk foam",
    price: 5.50,
},
{
    id: 'coffee7',
    img: "../img/pictures/coffee-7.svg",
    title: "Latte macchiato",
    text: "Espresso with frothed milk and chocolate",
    price: 5.50,
},
{
    id: 'coffee8',
    img: "../img/pictures/coffee-8.svg",
    title: "Coffee with cognac",
    text: "Fragrant black coffee with cognac and whipped cream",
    price: 6.50,
},
];

let teaItem = [{
    id: 'tea1',
    img: "../img/pictures/tea-1.svg",
    title: "Moroccan",
    text: "Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint",
    price: 4.50,
},
{
    id: 'tea2',
    img: "../img/pictures/tea-2.svg",
    title: "Ginger",
    text: "Original black tea with fresh ginger, lemon and honey",
    price: 5.00,
},
{
    id: 'tea3',
    img: "../img/pictures/tea-3.svg",
    title: "Cranberry",
    text: "Invigorating black tea with cranberry and honey",
    price: 5.00,
},
{
    id: 'tea4',
    img: "../img/pictures/tea-4.svg",
    title: "Sea buckthorn",
    text: "Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon",
    price: 5.50,
},
];

let dessertItem = [{
    id: 'dessert1',
    img: "../img/pictures/dessert-1.svg",
    title: "Marble cheesecake",
    text: "Philadelphia cheese with lemon zest on a light sponge cake and red currant jam",
    price: 3.50,
},
{
    id: 'dessert2',
    img: "../img/pictures/dessert-2.svg",
    title: "Red velvet",
    text: "Layer cake with cream cheese frosting",
    price: 4.00,
},
{
    id: 'dessert3',
    img: "../img/pictures/dessert-3.svg",
    title: "Cheesecakes",
    text: "Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar",
    price: 4.50,
},
{
    id: 'dessert4',
    img: "../img/pictures/dessert-4.svg",
    title: "Creme brulee",
    text: "Delicate creamy dessert in a caramel basket with wild berries",
    price: 4.00,
},
{
    id: 'dessert5',
    img: "../img/pictures/dessert-5.svg",
    title: "Pancakes",
    text: "Tender pancakes with strawberry jam and fresh strawberries",
    price: 4.50,
},
{
    id: 'dessert6',
    img: "../img/pictures/dessert-6.svg",
    title: "Honey cake",
    text: "Classic honey cake with delicate custard",
    price: 4.50,
},
{
    id: 'dessert7',
    img: "../img/pictures/dessert-7.svg",
    title: "Chocolate cake",
    text: "Cake with hot chocolate filling and nuts with dried apricots",
    price: 5.50,
},
{
    id: 'dessert8',
    img: "../img/pictures/dessert-8.svg",
    title: "Black forest",
    text: "A combination of thin sponge cake with cherry jam and light chocolate mousse",
    price: 6.50,
},
];